SOPERACIONINV = """CREATE TABLE IF NOT EXISTS "SOperacionInv"
(
   "FTI_AUTOINCREMENT" AUTOINC NOT NULL,
   "FTI_DOCUMENTO" VARCHAR(30) NOT NULL,
   "FTI_TIPO" INTEGER NOT NULL,
   "FTI_STATUS" INTEGER,
   "FTI_VISIBLE" BOOLEAN,
   "FTI_FECHAEMISION" TIMESTAMP,
   "FTI_DEPOSITOSOURCE" INTEGER,
   "FTI_DEPOSITODESTINO" INTEGER,
   "FTI_TOTALITEMS" INTEGER,
   "FTI_TOTALITEMSINICIAL" INTEGER,
   "FTI_MONEDA" INTEGER,
   "FTI_FACTORCAMBIO" FLOAT,
   "FTI_TOTALCOSTO" MONEY,
   "FTI_TOTALCOSTOREAL" MONEY,
   "FTI_CLASIFICACION" INTEGER,
   "FTI_DESCRIPCLASIFY" VARCHAR(80),
   "FTI_USER" INTEGER,
   "FTI_AUTORIZADOPOR" VARCHAR(100),
   "FTI_PROPOSITO" VARCHAR(50),
   "FTI_RESPONSABLE" VARCHAR(100),
   "FTI_DETALLE" MEMO,
   "FTI_TIENELOTES" BOOLEAN,
   "FTI_UPDATEITEMS" BOOLEAN,
   "FTI_TOTALBRUTO" MONEY,
   "FTI_DESCUENTO1PORCENT" MONEY,
   "FTI_DESCUENTO1MONTO" MONEY,
   "FTI_DESCUENTO1ORIGEN" SMALLINT,
   "FTI_DESCUENTO2PORCENT" MONEY,
   "FTI_DESCUENTO2MONTO" MONEY,
   "FTI_DESCUENTO2ORIGEN" SMALLINT,
   "FTI_DESCUENTOPARCIAL" MONEY,
   "FTI_FLETEPORCENT" MONEY,
   "FTI_FLETEMONEDA" MONEY,
   "FTI_FLETEORIGEN" SMALLINT,
   "FTI_BASEIMPONIBLE" MONEY,
   "FTI_BASEIMPONIBLE2" MONEY,
   "FTI_IMPUESTO1PORCENT" MONEY,
   "FTI_IMPUESTO1MONTO" MONEY,
   "FTI_IMPUESTO2PORCENT" MONEY,
   "FTI_IMPUESTO2MONTO" MONEY,
   "FTI_DESCUENTOCUADRE" MONEY,
   "FTI_TOTALNETO" MONEY,
   "FTI_FECHAVENCIDO" DATE,
   "FTI_DIASVENCIMIENTO" INTEGER,
   "FTI_RIFCLIENTE" VARCHAR(50),
   "FTI_NITCLIENTE" VARCHAR(50),
   "FTI_PERSONACONTACTO" VARCHAR(100),
   "FTI_TELEFONOCONTACTO" VARCHAR(100),
   "FTI_DIRECCIONDESPACHO" MEMO,
   "FTI_DETALLECOMENTARIO" MEMO,
   "FTI_ORDENCOMPRA" VARCHAR(50),
   "FTI_PLANILLAIMPORTACION" BLOB,
   "FTI_EXISTEPLANILLAIMPORTACION" BOOLEAN,
   "FTI_PORCENTFLETESINASIGNAR" MONEY,
   "FTI_SALDOOPERACION" MONEY,
   "FTI_MONEDAPAGO" INTEGER,
   "FTI_FORMADEPAGO" BLOB,
   "FTI_TOTALPRECIO" MONEY,
   "FTI_VUELTO" MONEY,
   "FTI_AUTORIZADOS" INTEGER,
   "FTI_EXCENTO" BOOLEAN,
   "FTI_COSTODEVENTA" MONEY,
   "FTI_TIPOOPERACIONORIGEN" INTEGER,
   "FTI_DOCUMENTOORIGEN" VARCHAR(30),
   "FTI_FROMCOMPUESTOS" BOOLEAN,
   "FTI_VENDEDORASIGNADO" VARCHAR(50),
   "FTI_ZONAVENTA" VARCHAR(25),
   "FTI_PENDINGFORPRINT" BOOLEAN,
   "FTI_COBRADORASIGNADO" VARCHAR(50),
   "FTI_COMISIONCOBROS" MONEY,
   "FTI_COMISIONCOBROSBLOQUEADA" BOOLEAN,
   "FTI_FACTURASLOTERANDOM" VARCHAR(20),
   "FTI_MULTIPLEVENDEDOR" BOOLEAN,
   "FTI_MULTIPLEDEPOSITO" BOOLEAN,
   "FTI_TIMESAVED" INTEGER,
   "FTI_TIPOPRECIO" INTEGER,
   "BASE_AUTOINCREMENT" AUTOINC,
   "FTI_SERIE" VARCHAR(20),
   "FTI_NAMEFORMATO" VARCHAR(50),
   "FTI_MACHINENAME" VARCHAR(50),
   "FTI_COMISIONVENTA" MONEY,
   "FTI_MONTOPAGADO" MONEY,
   "FTI_MONTOPERIODO" MONEY,
   "FTI_PORCENTPERIODO" MONEY,
   "FTI_HORA" TIME,
   "FTI_GUIADESPACHO" VARCHAR(10),
   "FTI_NORECIBOCAJA" VARCHAR(10),
   "FTI_CTOCOSTO" VARCHAR(30),
   "FTI_COSTOACTUALNACIONAL" MONEY,
   "FTI_COSTOACTUALEX" MONEY,
   "FTI_PREFIXINVENTARIO" VARCHAR(10),
   "FTI_NUMEROCONTROL" VARCHAR(15),
   "FTI_COSTOAJUSTADO" MONEY,
   "FTI_FACTORREFERENCIA" FLOAT,
   "FTI_FACTORREFERENCIA2" FLOAT,
   "FTI_FINICIAL" MONEY,
   "FTI_FINTERESES" MONEY,
   "FTI_FINTERESESP" MONEY,
   "FTI_FMANEJO" MONEY,
   "FTI_FMANEJOP" MONEY,
   "FTI_FEXTRAORDINARIA" MONEY,
   "FTI_FCTDEXTRAORDINARIA" INTEGER,
   "FTI_FINTEXTRAORDINARIA" MONEY,
   "FTI_FMTOCUOTA" MONEY,
   "FTI_FCTDCUOTA" INTEGER,
   "FTI_FCOBRANZA" MONEY,
   "FTI_TOTALFINANCIADO" MONEY,
   "FTI_DETALLEGIROS" BLOB,
   "FTI_SALDOFINANCIAR" MONEY,
   "FTI_PRIMERACUOTA" DATE,
   "FTI_CAPITALCUOTAEXTRA" MONEY,
   "FTI_CREDICARD" MEMO,
   "FTI_MAQUINAFISCAL" VARCHAR(50),
   "FTI_TOTALPAGINAS" INTEGER,
   "FTI_SUCURSALORIGEN" SMALLINT,
   "FTI_FECHALIBRO" TIMESTAMP,
   "FTI_IVAINTERESES" MONEY,
   "FTI_REIMPRESAFISCAL" BOOLEAN,
   "FTI_DCTOFISCALORIGEN" VARCHAR(50),
   "FTI_FECHAFACTURA" DATE,
   "FTI_DCTOIVA" FLOAT,
   "FTI_MONEDACAMBIO" VARCHAR(10),
   "FTI_TIPOFACTORCAMBIO" SMALLINT,
   "FTI_ORIGENCAMBIO" SMALLINT,
   "FTI_FACTORVUELTO" FLOAT,
   "FTI_CODECAMBIO" VARCHAR(10),
   "FTI_VUELTOORG" MONEY,
   "FTI_VTANAPAGO" SMALLINT,
   "FTI_MULTIVUELTO" BLOB,
   "FTI_EXTRAFIELD01" VARCHAR(40),
   "FTI_EXTRAFIELD02" VARCHAR(40),
   "FTI_EXTRAFIELD03" VARCHAR(40),
   "FTI_EXTRAFIELD04" VARCHAR(40),
   "FTI_EXTRAFIELD05" VARCHAR(250),
   "FTI_BASEIGTF" FLOAT,
   "FTI_IMPRENTAASIGNACION" VARCHAR(15),
   "FTI_IMPRENTAHORA" VARCHAR(15),
   "FTI_STATUSIMPRENTA" SMALLINT,
   "FTI_IMPRENTADOCORIGEN" VARCHAR(15),
   "FTI_IMPRENTAMOTIVO" VARCHAR(255),
   "FTI_IMPRENTAFECHAORIGEN" DATE,
   "FTI_IMPRENTASERIEORIGEN" VARCHAR(15),
   "FTI_IMPRENTAMTOORIGEN" FLOAT,
   "FTI_EXTRAFIELD06" VARCHAR(250),
   "FTI_MTOOTROSCARGOS" FLOAT,
PRIMARY KEY ("FTI_AUTOINCREMENT") COMPRESS NONE
LOCALE CODE 0
);

CREATE INDEX IF NOT EXISTS "FTI_KEYDOCUMENTO" ON "SOperacionInv" ("FTI_TIPO","FTI_STATUS","FTI_DOCUMENTO","FTI_USER");
CREATE INDEX IF NOT EXISTS "FTI_KEYFECHA" ON "SOperacionInv" ("FTI_TIPO","FTI_STATUS","FTI_FECHAEMISION","FTI_USER");
CREATE NOCASE INDEX IF NOT EXISTS "FTI_KEYPERSONACONTACTO" ON "SOperacionInv" ("FTI_TIPO","FTI_STATUS","FTI_PERSONACONTACTO","FTI_USER");
CREATE INDEX IF NOT EXISTS "FTI_KEYDOCUMENTOSHARE" ON "SOperacionInv" ("FTI_USER","FTI_TIPO","FTI_STATUS","FTI_DOCUMENTO");
CREATE INDEX IF NOT EXISTS "FTI_KEYFECHASHARE" ON "SOperacionInv" ("FTI_USER","FTI_TIPO","FTI_STATUS","FTI_FECHAEMISION");
CREATE NOCASE INDEX IF NOT EXISTS "FTI_KEYPERSONACONTACTOSHARE" ON "SOperacionInv" ("FTI_USER","FTI_TIPO","FTI_STATUS","FTI_PERSONACONTACTO");
CREATE INDEX IF NOT EXISTS "FTI_KEYLOTE" ON "SOperacionInv" ("FTI_TIPO","FTI_FACTURASLOTERANDOM");
CREATE INDEX IF NOT EXISTS "FTI_KEYORIGEN" ON "SOperacionInv" ("FTI_TIPO","FTI_STATUS","FTI_DOCUMENTOORIGEN");
CREATE INDEX IF NOT EXISTS "FTI_KEYREPORT" ON "SOperacionInv" ("FTI_TIPO","FTI_FECHAEMISION");
CREATE INDEX IF NOT EXISTS "FTI_VENDEDOR" ON "SOperacionInv" ("FTI_VENDEDORASIGNADO","FTI_FECHAEMISION","FTI_TIPO","FTI_RESPONSABLE");
CREATE INDEX IF NOT EXISTS "FTI_KEYGENERADOR" ON "SOperacionInv" ("FTI_RESPONSABLE","FTI_TIPO","FTI_STATUS","FTI_FECHAEMISION");
CREATE INDEX IF NOT EXISTS "FTI_KEYRESPONSABLE" ON "SOperacionInv" ("FTI_TIPO","FTI_STATUS","FTI_RESPONSABLE","FTI_USER");
CREATE INDEX IF NOT EXISTS "FTI_KEYRESPONSABLESHARE" ON "SOperacionInv" ("FTI_TIPO","FTI_STATUS","FTI_RESPONSABLE");
CREATE INDEX IF NOT EXISTS "FTI_KEYLIBRO" ON "SOperacionInv" ("FTI_TIPO","FTI_FECHALIBRO");
CREATE INDEX IF NOT EXISTS "FTI_KEYRIF" ON "SOperacionInv" ("FTI_TIPO","FTI_RIFCLIENTE","FTI_FECHAEMISION")


"""
SDETALLEVENTA = """
CREATE TABLE IF NOT EXISTS "SDetalleVenta"
(
   "FDI_TIPOOPERACION" INTEGER NOT NULL,
   "FDI_CODIGO" VARCHAR(40) NOT NULL,
   "FDI_LINEA" INTEGER NOT NULL,
   "FDI_DOCUMENTO" VARCHAR(30) NOT NULL,
   "FDI_AUTOINCREMENT" AUTOINC NOT NULL,
   "FDI_CLIENTEPROVEEDOR" VARCHAR(40),
   "FDI_DOCUMENTOORIGEN" VARCHAR(20),
   "FDI_LINEAORIGEN" INTEGER,
   "FDI_CLASIFICACION" INTEGER,
   "FDI_STATUS" INTEGER,
   "FDI_VISIBLE" BOOLEAN,
   "FDI_COSTO" MONEY,
   "FDI_CANTIDAD" FLOAT,
   "FDI_CANTIDADPENDIENTE" FLOAT,
   "FDI_LOTE" VARCHAR(100),
   "FDI_LOTERANDOM" INTEGER,
   "FDI_NEWLOTE" BOOLEAN,
   "FDI_DEPOSITOSOURCE" INTEGER,
   "FDI_DEPOSITOTARGET" INTEGER,
   "FDI_OPERACION_AUTOINCREMENT" INTEGER,
   "FDI_DECIMALES" BOOLEAN,
   "FDI_DECIMALESPEN" BOOLEAN,
   "FDI_SERIALNUMBER" INTEGER,
   "FDI_USASERIALES" BOOLEAN,
   "FDI_USADEPOSITOS" BOOLEAN,
   "FDI_COSTOOPERACION" MONEY,
   "FDI_MEMODETALLE" MEMO,
   "FDI_MONEDA" INTEGER,
   "FDI_FACTORCAMBIO" FLOAT,
   "FDI_DETALLECOSTOSIMPORTACION" BLOB,
   "FDI_DETALLEPLANILLAIMPORTACION" BLOB,
   "FDI_EXISTEDETALLEIMPORTACION" BOOLEAN,
   "FDI_EXISTEDETALLEDECOSTOS" BOOLEAN,
   "FDI_ALICUOTAFLETEOTROS" MONEY,
   "FDI_IMPUESTO1" MONEY,
   "FDI_PORCENTIMPUESTO1" BOOLEAN,
   "FDI_MONTOIMPUESTO1" MONEY,
   "FDI_IMPUESTO2" MONEY,
   "FDI_PORCENTIMPUESTO2" BOOLEAN,
   "FDI_MONTOIMPUESTO2" MONEY,
   "FDI_ORIGENPRICE" INTEGER,
   "FDI_PORCENTDESCPARCIAL" MONEY,
   "FDI_DESCUENTOPARCIAL" MONEY,
   "FDI_PRECIOSINDESCUENTO" MONEY,
   "FDI_PRECIOCONDESCUENTO" MONEY,
   "FDI_PRECIODEVENTA" MONEY,
   "FDI_ROUNDDESCTPARCIAL" INTEGER,
   "FDI_COMISIONFIJA" MONEY,
   "FDI_COMISIONFIJAP" BOOLEAN,
   "FDI_UNDDESCARGA" MONEY,
   "FDI_UNDCAPACIDAD" MONEY,
   "FDI_UNDDETALLADA" BOOLEAN,
   "FDI_INDEXPRICES" INTEGER,
   "FDI_PARTESUSANSERIALES" BOOLEAN,
   "FDI_COSTODEVENTAS" MONEY,
   "FDI_DESCRIPCIONOFERTA" VARCHAR(100),
   "FDI_VENDEDORASIGNADO" VARCHAR(50),
   "FDI_MONTOCOMISION" MONEY,
   "FDI_PRECIOBASECOMISION" MONEY,
   "FDI_COMISIONBLOQUEADA" BOOLEAN,
   "FDI_COMISIONYAPAGADA" BOOLEAN,
   "FDI_DOCUMENTOLIBERACION" VARCHAR(20),
   "FDI_TIPODECOMISION" INTEGER,
   "FDI_PRICEFORCOMISION" INTEGER,
   "FDI_FECHAOPERACION" DATE,
   "FDI_USER" INTEGER,
   "FDI_PORCENTDESCUENTO1" MONEY,
   "FDI_PORCENTDESCUENTO2" MONEY,
   "FDI_COSTOSUPDATE" BOOLEAN,
   "BASE_AUTOINCREMENT" AUTOINC,
   "FDI_TOTALPESO" MONEY,
   "FDI_CTOCOSTO" INTEGER,
   "FDI_AUTORIZADO" VARCHAR(10),
   "FDI_MARKPERIODO" BOOLEAN,
   "FDI_CTOCOSTOSTR" VARCHAR(30),
   "FDI_COSTOACTUALNACIONAL" MONEY,
   "FDI_COSTOACTUALEXT" MONEY,
   "FDI_PREFIXINVENTARIO" VARCHAR(10),
   "FDI_COSTOAJUSTADO" MONEY,
   "FDI_FECHALIBRO" DATE,
   "FDI_MONTOLIQUIDADO" MONEY,
   "FDI_TIPODOCUMENTOORIGEN" SMALLINT,
   "FDI_STATUSDOCUMENTOORIGEN" SMALLINT,
   "FDI_DCTOIVA" FLOAT,
   "FDI_MONTOIMPUESTO1DCTO" MONEY,
   "FDI_PRECIODEVENTADCTO" MONEY,
PRIMARY KEY ("FDI_TIPOOPERACION","FDI_CODIGO","FDI_LINEA","FDI_DOCUMENTO","FDI_AUTOINCREMENT") COMPRESS NONE
LOCALE CODE 0
);

CREATE INDEX IF NOT EXISTS "FDI_KEYLOAD" ON "SDetalleVenta" ("FDI_TIPOOPERACION","FDI_LINEA","FDI_CODIGO");
CREATE INDEX IF NOT EXISTS "FDI_KEYINFO" ON "SDetalleVenta" ("FDI_OPERACION_AUTOINCREMENT","FDI_STATUS","FDI_LINEA","FDI_DOCUMENTO");
CREATE INDEX IF NOT EXISTS "FDI_KEYDELETE" ON "SDetalleVenta" ("FDI_OPERACION_AUTOINCREMENT","FDI_DOCUMENTO","FDI_CODIGO","FDI_LINEA");
CREATE INDEX IF NOT EXISTS "FDI_KEYPLANILLA" ON "SDetalleVenta" ("FDI_AUTOINCREMENT","FDI_CODIGO");
CREATE INDEX IF NOT EXISTS "FDI_KEYFECHA" ON "SDetalleVenta" ("FDI_TIPOOPERACION","FDI_CODIGO","FDI_FECHAOPERACION");
CREATE INDEX IF NOT EXISTS "FDI_KEYREPMOV" ON "SDetalleVenta" ("FDI_CODIGO","FDI_FECHAOPERACION","FDI_TIPOOPERACION");
CREATE INDEX IF NOT EXISTS "FDI_KEYCOMPUESTO" ON "SDetalleVenta" ("FDI_TIPOOPERACION","FDI_DOCUMENTOORIGEN","FDI_FECHAOPERACION","FDI_LINEAORIGEN");
CREATE INDEX IF NOT EXISTS "FDI_KEYVENDEDOR" ON "SDetalleVenta" ("FDI_VENDEDORASIGNADO","FDI_FECHAOPERACION","FDI_TIPOOPERACION","FDI_CLIENTEPROVEEDOR");
CREATE INDEX IF NOT EXISTS "FDI_KEYLOADFECHA" ON "SDetalleVenta" ("FDI_TIPOOPERACION","FDI_FECHAOPERACION");
 """
SDETALLEINV = """ CREATE TABLE IF NOT EXISTS "SDetalleInv"
(
   "FDI_TIPOOPERACION" INTEGER NOT NULL,
   "FDI_CODIGO" VARCHAR(40) NOT NULL,
   "FDI_LINEA" INTEGER NOT NULL,
   "FDI_DOCUMENTO" VARCHAR(30) NOT NULL,
   "FDI_AUTOINCREMENT" AUTOINC NOT NULL,
   "FDI_CLIENTEPROVEEDOR" VARCHAR(40),
   "FDI_TIPODOCUMENTOORIGEN" SMALLINT,
   "FDI_STATUSDOCUMENTOORIGEN" SMALLINT,
   "FDI_DOCUMENTOORIGEN" VARCHAR(20),
   "FDI_LINEAORIGEN" INTEGER,
   "FDI_CLASIFICACION" INTEGER,
   "FDI_STATUS" INTEGER,
   "FDI_VISIBLE" BOOLEAN,
   "FDI_COSTO" MONEY,
   "FDI_CANTIDAD" FLOAT,
   "FDI_CANTIDADPENDIENTE" FLOAT,
   "FDI_LOTE" VARCHAR(100),
   "FDI_LOTERANDOM" INTEGER,
   "FDI_NEWLOTE" BOOLEAN,
   "FDI_DEPOSITOSOURCE" INTEGER,
   "FDI_DEPOSITOTARGET" INTEGER,
   "FDI_OPERACION_AUTOINCREMENT" INTEGER,
   "FDI_DECIMALES" BOOLEAN,
   "FDI_DECIMALESPEN" BOOLEAN,
   "FDI_SERIALNUMBER" INTEGER,
   "FDI_USASERIALES" BOOLEAN,
   "FDI_USADEPOSITOS" BOOLEAN,
   "FDI_COSTOOPERACION" MONEY,
   "FDI_MEMODETALLE" MEMO,
   "FDI_MONEDA" INTEGER,
   "FDI_FACTORCAMBIO" FLOAT,
   "FDI_DETALLECOSTOSIMPORTACION" BLOB,
   "FDI_DETALLEPLANILLAIMPORTACION" BLOB,
   "FDI_EXISTEDETALLEIMPORTACION" BOOLEAN,
   "FDI_EXISTEDETALLEDECOSTOS" BOOLEAN,
   "FDI_ALICUOTAFLETEOTROS" MONEY,
   "FDI_IMPUESTO1" MONEY,
   "FDI_PORCENTIMPUESTO1" BOOLEAN,
   "FDI_MONTOIMPUESTO1" MONEY,
   "FDI_IMPUESTO2" MONEY,
   "FDI_PORCENTIMPUESTO2" BOOLEAN,
   "FDI_MONTOIMPUESTO2" MONEY,
   "FDI_ORIGENPRICE" INTEGER,
   "FDI_PORCENTDESCPARCIAL" MONEY,
   "FDI_DESCUENTOPARCIAL" MONEY,
   "FDI_PRECIOSINDESCUENTO" MONEY,
   "FDI_PRECIOCONDESCUENTO" MONEY,
   "FDI_PRECIODEVENTA" MONEY,
   "FDI_ROUNDDESCTPARCIAL" INTEGER,
   "FDI_COMISIONFIJA" MONEY,
   "FDI_COMISIONFIJAP" BOOLEAN,
   "FDI_UNDDESCARGA" MONEY,
   "FDI_UNDCAPACIDAD" MONEY,
   "FDI_UNDDETALLADA" BOOLEAN,
   "FDI_INDEXPRICES" INTEGER,
   "FDI_PARTESUSANSERIALES" BOOLEAN,
   "FDI_COSTODEVENTAS" MONEY,
   "FDI_DESCRIPCIONOFERTA" VARCHAR(100),
   "FDI_VENDEDORASIGNADO" VARCHAR(50),
   "FDI_MONTOCOMISION" MONEY,
   "FDI_PRECIOBASECOMISION" MONEY,
   "FDI_COMISIONBLOQUEADA" BOOLEAN,
   "FDI_COMISIONYAPAGADA" BOOLEAN,
   "FDI_DOCUMENTOLIBERACION" VARCHAR(20),
   "FDI_TIPODECOMISION" INTEGER,
   "FDI_PRICEFORCOMISION" INTEGER,
   "FDI_FECHAOPERACION" DATE,
   "FDI_USER" INTEGER,
   "FDI_PORCENTDESCUENTO1" MONEY,
   "FDI_PORCENTDESCUENTO2" MONEY,
   "FDI_COSTOSUPDATE" BOOLEAN,
   "BASE_AUTOINCREMENT" AUTOINC,
   "FDI_TOTALPESO" MONEY,
   "FDI_CTOCOSTO" INTEGER,
   "FDI_AUTORIZADO" VARCHAR(10),
   "FDI_MARKPERIODO" BOOLEAN,
   "FDI_CTOCOSTOSTR" VARCHAR(30),
   "FDI_COSTOACTUALNACIONAL" MONEY,
   "FDI_COSTOACTUALEXT" MONEY,
   "FDI_PREFIXINVENTARIO" VARCHAR(10),
   "FDI_COSTOAJUSTADO" MONEY,
   "FDI_FECHALIBRO" DATE,
PRIMARY KEY ("FDI_TIPOOPERACION","FDI_CODIGO","FDI_LINEA","FDI_DOCUMENTO","FDI_AUTOINCREMENT") COMPRESS NONE
LOCALE CODE 0
);

CREATE INDEX IF NOT EXISTS "FDI_KEYLOAD" ON "SDetalleInv" ("FDI_TIPOOPERACION","FDI_LINEA","FDI_CODIGO");
CREATE INDEX IF NOT EXISTS "FDI_KEYINFO" ON "SDetalleInv" ("FDI_OPERACION_AUTOINCREMENT","FDI_STATUS","FDI_LINEA","FDI_DOCUMENTO");
CREATE INDEX IF NOT EXISTS "FDI_KEYDELETE" ON "SDetalleInv" ("FDI_OPERACION_AUTOINCREMENT","FDI_DOCUMENTO","FDI_CODIGO","FDI_LINEA");
CREATE INDEX IF NOT EXISTS "FDI_KEYPLANILLA" ON "SDetalleInv" ("FDI_AUTOINCREMENT","FDI_CODIGO");
CREATE INDEX IF NOT EXISTS "FDI_KEYFECHA" ON "SDetalleInv" ("FDI_TIPOOPERACION","FDI_CODIGO","FDI_FECHAOPERACION");
CREATE INDEX IF NOT EXISTS "FDI_KEYREPMOV" ON "SDetalleInv" ("FDI_CODIGO","FDI_FECHAOPERACION","FDI_TIPOOPERACION");
CREATE INDEX IF NOT EXISTS "FDI_KEYCOMPUESTO" ON "SDetalleInv" ("FDI_TIPOOPERACION","FDI_DOCUMENTOORIGEN","FDI_FECHAOPERACION","FDI_LINEAORIGEN");
CREATE INDEX IF NOT EXISTS "FDI_KEYVENDEDOR" ON "SDetalleInv" ("FDI_VENDEDORASIGNADO","FDI_FECHAOPERACION","FDI_TIPOOPERACION","FDI_CLIENTEPROVEEDOR");
CREATE INDEX IF NOT EXISTS "FDI_KEYLOADFECHA" ON "SDetalleInv" ("FDI_TIPOOPERACION","FDI_FECHAOPERACION");
"""

SDETALLEPARTES =""" CREATE TABLE IF NOT EXISTS "SDetallePartes"
(
   "FDC_AUTOINCOPERACION" INTEGER,
   "FDC_TIPOOPERACION" INTEGER,
   "FDC_STATUSOPERACION" INTEGER,
   "FDC_RANDOMITEM" INTEGER,
   "FDC_CODEPRODUCTO" VARCHAR(30),
   "FDC_CODEPARTE" VARCHAR(30),
   "FDC_CANTIDAD" FLOAT,
   "FDC_CANTIDADPRODUCTO" FLOAT,
   "FDC_LINEA" INTEGER,
   "FDC_COSTOOPERACION" MONEY,
   "FDC_FACTOROPERACION" FLOAT,
   "FDC_NUMEROOPERACION" VARCHAR(20),
   "BASE_AUTOINCREMENT" INTEGER,
   "FDC_USASERIALES" BOOLEAN,
   "FDC_DOCUMENTOORIGEN" VARCHAR(20),
   "FDC_TIPOOPERACIONORIGEN" INTEGER,
   "FDC_FECHAOPERACION" DATE,
   "FDC_MONEDA" INTEGER,
   "FDC_CLASIFICACION" INTEGER,
   "FDC_USUARIO" VARCHAR(30),
PRIMARY KEY ("FDC_AUTOINCOPERACION","FDC_RANDOMITEM","FDC_LINEA") COMPRESS NONE
LOCALE CODE 0
USER MAJOR VERSION 1
);

CREATE INDEX IF NOT EXISTS "FDC_KEYPRODUCTO" ON "SDetallePartes" ("FDC_CODEPRODUCTO");
"""
SDETALLECOMPRA = """
CREATE TABLE IF NOT EXISTS "SDetalleCompra"
(
   "FDI_TIPOOPERACION" INTEGER NOT NULL,
   "FDI_CODIGO" VARCHAR(40) NOT NULL,
   "FDI_LINEA" INTEGER NOT NULL,
   "FDI_DOCUMENTO" VARCHAR(30) NOT NULL,
   "FDI_AUTOINCREMENT" AUTOINC NOT NULL,
   "FDI_CLIENTEPROVEEDOR" VARCHAR(40),
   "FDI_TIPODOCUMENTOORIGEN" SMALLINT,
   "FDI_STATUSDOCUMENTOORIGEN" SMALLINT,
   "FDI_DOCUMENTOORIGEN" VARCHAR(20),
   "FDI_LINEAORIGEN" INTEGER,
   "FDI_CLASIFICACION" INTEGER,
   "FDI_STATUS" INTEGER,
   "FDI_VISIBLE" BOOLEAN,
   "FDI_COSTO" MONEY,
   "FDI_CANTIDAD" FLOAT,
   "FDI_CANTIDADPENDIENTE" FLOAT,
   "FDI_LOTE" VARCHAR(100),
   "FDI_LOTERANDOM" INTEGER,
   "FDI_NEWLOTE" BOOLEAN,
   "FDI_DEPOSITOSOURCE" INTEGER,
   "FDI_DEPOSITOTARGET" INTEGER,
   "FDI_OPERACION_AUTOINCREMENT" INTEGER,
   "FDI_DECIMALES" BOOLEAN,
   "FDI_DECIMALESPEN" BOOLEAN,
   "FDI_SERIALNUMBER" INTEGER,
   "FDI_USASERIALES" BOOLEAN,
   "FDI_USADEPOSITOS" BOOLEAN,
   "FDI_COSTOOPERACION" MONEY,
   "FDI_MEMODETALLE" MEMO,
   "FDI_MONEDA" INTEGER,
   "FDI_FACTORCAMBIO" FLOAT,
   "FDI_DETALLECOSTOSIMPORTACION" BLOB,
   "FDI_DETALLEPLANILLAIMPORTACION" BLOB,
   "FDI_EXISTEDETALLEIMPORTACION" BOOLEAN,
   "FDI_EXISTEDETALLEDECOSTOS" BOOLEAN,
   "FDI_ALICUOTAFLETEOTROS" MONEY,
   "FDI_IMPUESTO1" MONEY,
   "FDI_PORCENTIMPUESTO1" BOOLEAN,
   "FDI_MONTOIMPUESTO1" MONEY,
   "FDI_IMPUESTO2" MONEY,
   "FDI_PORCENTIMPUESTO2" BOOLEAN,
   "FDI_MONTOIMPUESTO2" MONEY,
   "FDI_ORIGENPRICE" INTEGER,
   "FDI_PORCENTDESCPARCIAL" MONEY,
   "FDI_DESCUENTOPARCIAL" MONEY,
   "FDI_PRECIOSINDESCUENTO" MONEY,
   "FDI_PRECIOCONDESCUENTO" MONEY,
   "FDI_PRECIODEVENTA" MONEY,
   "FDI_ROUNDDESCTPARCIAL" INTEGER,
   "FDI_COMISIONFIJA" MONEY,
   "FDI_COMISIONFIJAP" BOOLEAN,
   "FDI_UNDDESCARGA" MONEY,
   "FDI_UNDCAPACIDAD" MONEY,
   "FDI_UNDDETALLADA" BOOLEAN,
   "FDI_INDEXPRICES" INTEGER,
   "FDI_PARTESUSANSERIALES" BOOLEAN,
   "FDI_COSTODEVENTAS" MONEY,
   "FDI_DESCRIPCIONOFERTA" VARCHAR(100),
   "FDI_VENDEDORASIGNADO" VARCHAR(50),
   "FDI_MONTOCOMISION" MONEY,
   "FDI_PRECIOBASECOMISION" MONEY,
   "FDI_COMISIONBLOQUEADA" BOOLEAN,
   "FDI_COMISIONYAPAGADA" BOOLEAN,
   "FDI_DOCUMENTOLIBERACION" VARCHAR(20),
   "FDI_TIPODECOMISION" INTEGER,
   "FDI_PRICEFORCOMISION" INTEGER,
   "FDI_FECHAOPERACION" DATE,
   "FDI_USER" INTEGER,
   "FDI_PORCENTDESCUENTO1" MONEY,
   "FDI_PORCENTDESCUENTO2" MONEY,
   "FDI_COSTOSUPDATE" BOOLEAN,
   "BASE_AUTOINCREMENT" AUTOINC,
   "FDI_TOTALPESO" MONEY,
   "FDI_CTOCOSTO" INTEGER,
   "FDI_AUTORIZADO" VARCHAR(10),
   "FDI_MARKPERIODO" BOOLEAN,
   "FDI_CTOCOSTOSTR" VARCHAR(30),
   "FDI_COSTOACTUALNACIONAL" MONEY,
   "FDI_COSTOACTUALEXT" MONEY,
   "FDI_PREFIXINVENTARIO" VARCHAR(10),
   "FDI_COSTOAJUSTADO" MONEY,
   "FDI_FECHALIBRO" DATE,
PRIMARY KEY ("FDI_TIPOOPERACION","FDI_CODIGO","FDI_LINEA","FDI_DOCUMENTO","FDI_AUTOINCREMENT") COMPRESS NONE
LOCALE CODE 0
);

CREATE INDEX IF NOT EXISTS "FDI_KEYLOAD" ON "SDetalleCompra" ("FDI_TIPOOPERACION","FDI_LINEA","FDI_CODIGO");
CREATE INDEX IF NOT EXISTS "FDI_KEYINFO" ON "SDetalleCompra" ("FDI_OPERACION_AUTOINCREMENT","FDI_STATUS","FDI_LINEA","FDI_DOCUMENTO");
CREATE INDEX IF NOT EXISTS "FDI_KEYDELETE" ON "SDetalleCompra" ("FDI_OPERACION_AUTOINCREMENT","FDI_DOCUMENTO","FDI_CODIGO","FDI_LINEA");
CREATE INDEX IF NOT EXISTS "FDI_KEYPLANILLA" ON "SDetalleCompra" ("FDI_AUTOINCREMENT","FDI_CODIGO");
CREATE INDEX IF NOT EXISTS "FDI_KEYFECHA" ON "SDetalleCompra" ("FDI_TIPOOPERACION","FDI_CODIGO","FDI_FECHAOPERACION");
CREATE INDEX IF NOT EXISTS "FDI_KEYREPMOV" ON "SDetalleCompra" ("FDI_CODIGO","FDI_FECHAOPERACION","FDI_TIPOOPERACION");
CREATE INDEX IF NOT EXISTS "FDI_KEYCOMPUESTO" ON "SDetalleCompra" ("FDI_TIPOOPERACION","FDI_DOCUMENTOORIGEN","FDI_FECHAOPERACION","FDI_LINEAORIGEN");
CREATE INDEX IF NOT EXISTS "FDI_KEYVENDEDOR" ON "SDetalleCompra" ("FDI_VENDEDORASIGNADO","FDI_FECHAOPERACION","FDI_TIPOOPERACION","FDI_CLIENTEPROVEEDOR");
CREATE INDEX IF NOT EXISTS "FDI_KEYLOADFECHA" ON "SDetalleCompra" ("FDI_TIPOOPERACION","FDI_FECHAOPERACION");
"""
SCUENTASXCOBRAR = """CREATE TABLE IF NOT EXISTS "Scuentasxcobrar"
(
   "FCC_CODIGO" VARCHAR(30),
   "FCC_FECHAEMISION" TIMESTAMP,
   "FCC_CODIGOUNICO" AUTOINC,
   "FCC_CODAUTORIZADO" VARCHAR(10),
   "FCC_DOCUMENTOAPARTADO" VARCHAR(50),
   "FCC_NUMERO" VARCHAR(40),
   "FCC_CODIGOUNICO2" INTEGER,
   "FCC_NUMERO2" VARCHAR(40),
   "FCC_TIPOTRANSACCION" INTEGER,
   "FCC_TIPOOPERACION" VARCHAR(10),
   "FCC_DESCRIPCIONMOV" MEMO,
   "FCC_FECHAVENCIMIENTO" TIMESTAMP,
   "FCC_FECHAPROXIMA" TIMESTAMP,
   "FCC_MONTODOCUMENTO" MONEY,
   "FCC_SALDODOCUMENTO" MONEY,
   "FCC_SALDOMONEDAEXT" MONEY,
   "FCC_ULTABONODCTO" VARCHAR(20),
   "FCC_ULTABONOMTO" MONEY,
   "FCC_ULTFECHAABONO" TIMESTAMP,
   "FCC_IMPUESTOORG" MONEY,
   "FCC_AFECTACOMISIONES" BOOLEAN,
   "FCC_AFECTAVENTASMES" BOOLEAN,
   "FCC_AFECTALIBROVENTAS" BOOLEAN,
   "FCC_MTOCOMISION" MONEY,
   "FCC_COSTOOPERACION" MONEY,
   "FCC_ESPAGO" BOOLEAN,
   "FCC_ESCHEQUE" BOOLEAN,
   "FCC_NROVENDEDOR" VARCHAR(30),
   "FCC_ESRETENCION" BOOLEAN,
   "FCC_FLAGAUDITORIA" BOOLEAN,
   "FCC_MONTORETENCION" MONEY,
   "FCC_INCLUIRLIBROIVA" BOOLEAN,
   "FCC_MONTOIVA" MONEY,
   "FCC_CODERETENCION" VARCHAR(20),
   "FCC_BASERETENCION" MONEY,
   "FCC_BASEIMPONIBLE" MONEY,
   "FCC_BASEIMPONIBLE2" MONEY,
   "FCC_MULTIPLERETENCION" BOOLEAN,
   "FCC_MONTOMONEDAEXT" MONEY,
   "FCC_FACTORCAMBIO" FLOAT,
   "FCC_IMPUESTO1" MONEY,
   "FCC_IMPUESTO1PORCENT" BOOLEAN,
   "FCC_MTOIMPUESTO1" MONEY,
   "FCC_IMPUESTO2" MONEY,
   "FCC_IMPUESTO2PORCENT" BOOLEAN,
   "FCC_MTOIMPUESTO2" MONEY,
   "FCC_ESCHEQUEDEVUELTO" BOOLEAN,
   "FCC_VIENEDE" INTEGER,
   "FCC_FORMAPAGO" BLOB,
   "FCC_MONTOPAGOADELANTADO" MONEY,
   "FCC_DEPOSITADO" BOOLEAN,
   "FCC_USUARIO" INTEGER,
   "FCC_DOCUMENTOORIGEN" VARCHAR(100),
   "FCC_DOCUMENTOAFECTADO" VARCHAR(30),
   "FCC_MONEDA" INTEGER,
   "FCC_FECHARECEPCION" DATE,
   "FCC_MARKPERIODO" BOOLEAN,
   "FCC_PAGOORIGINAL" MONEY,
   "FCC_CONVERTED" BOOLEAN,
   "FCC_ULTFECHAMORA" DATE,
   "FCC_ULTFECHADESCUENTO" DATE,
   "BASE_AUTOINCREMENT" AUTOINC,
   "FCC_HORAEMISION" TIME,
   "FCC_CONTROL" VARCHAR(20),
   "FCC_MONTOORIGINAL" MONEY,
   "FCC_MONTOORIGINALEXT" MONEY,
   "FCC_MACHINENAME" VARCHAR(250),
   "FCC_ORDENPAGO" VARCHAR(10),
   "FCC_SERIE" VARCHAR(30),
   "FCC_CTOCOSTO" VARCHAR(30),
   "FCC_COMISIONYAPAGADA" BOOLEAN,
   "FCC_MONTOLIQUIDADO" MONEY,
   "FCC_SINCREDITOFISCAL" BOOLEAN,
   "FCC_VTANAPAGO" SMALLINT,
   "FCC_MONEDACAMBIO" VARCHAR(10),
   "FCC_ORIGENCAMBIO" SMALLINT,
   "FCC_CODECAMBIO" VARCHAR(10),
   "FCC_VUELTOORG" MONEY,
   "FCC_FACTORREFERENCIA" FLOAT,
   "FCC_FACTORVUELTO" FLOAT,
   "FCC_FACTORVUELTOTIPO" SMALLINT,
   "FCC_ADELANTOXCAMBIO" SMALLINT,
   "FCC_FACTORREFERENCIA2" FLOAT,
   "FCC_MULTIVUELTO" BLOB,
   "FCC_BASEIGTF" FLOAT,
   "FCC_IMPRENTAASIGNACION" VARCHAR(15),
   "FCC_IMPRENTAHORA" VARCHAR(15),
   "FCC_STATUSIMPRENTA" SMALLINT,
   "FCC_IDDOCUMENTOORIGEN" VARCHAR(20),
   "FCC_IDSERIEDOCORIGEN" VARCHAR(20),
   "FCC_IDMTODOCORIGEN" FLOAT,
   "FCC_IDFECHADOCORIGEN" DATE,
   "FCC_IDMOTIVODOCORIGEN" VARCHAR(255),
   "FCC_REIMPRESIONFISCAL" VARCHAR(10),
NOCASE PRIMARY KEY ("FCC_CODIGO","FCC_FECHAEMISION","FCC_CODIGOUNICO") COMPRESS NONE
LOCALE CODE 0
);

CREATE UNIQUE INDEX IF NOT EXISTS "FCC_KEYAUTORIZADOS" ON "Scuentasxcobrar" ("FCC_CODIGO","FCC_CODAUTORIZADO","FCC_FECHAEMISION","FCC_CODIGOUNICO");
CREATE NOCASE INDEX IF NOT EXISTS "FCC_KEYPAGOSFACT" ON "Scuentasxcobrar" ("FCC_CODIGO","FCC_NUMERO","FCC_TIPOTRANSACCION","FCC_FECHAEMISION");
CREATE UNIQUE INDEX IF NOT EXISTS "FCC_KEYAUTOINC" ON "Scuentasxcobrar" ("FCC_CODIGOUNICO");
CREATE NOCASE INDEX IF NOT EXISTS "FCC_KEYNUMERO2" ON "Scuentasxcobrar" ("FCC_CODIGO","FCC_NUMERO2","FCC_CODIGOUNICO2");
CREATE INDEX IF NOT EXISTS "FCC_KEYAPARTADOS" ON "Scuentasxcobrar" ("FCC_CODIGO","FCC_DOCUMENTOAPARTADO","FCC_TIPOTRANSACCION");
CREATE INDEX IF NOT EXISTS "FCC_KEYFECHA" ON "Scuentasxcobrar" ("FCC_FECHAEMISION","FCC_TIPOTRANSACCION","FCC_CODIGO");
CREATE INDEX IF NOT EXISTS "FCC_KEYVENDEDOR" ON "Scuentasxcobrar" ("FCC_NROVENDEDOR","FCC_CODIGO","FCC_FECHAEMISION");
CREATE INDEX IF NOT EXISTS "FCC_KEYREPORTE" ON "Scuentasxcobrar" ("FCC_TIPOTRANSACCION","FCC_FECHAEMISION");
CREATE INDEX IF NOT EXISTS "FCC_KEYCIERRE" ON "Scuentasxcobrar" ("FCC_CODIGO","FCC_CODIGOUNICO2");
CREATE INDEX IF NOT EXISTS "FCC_KEYTIPO" ON "Scuentasxcobrar" ("FCC_CODIGO","FCC_TIPOTRANSACCION");
 """
STRANSBANCO = """CREATE TABLE IF NOT EXISTS "Stransbanco"
(
   "FTB_BANCO" VARCHAR(30),
   "FTB_TIPO" SMALLINT,
   "FTB_FECHA" TIMESTAMP,
   "FTB_STATUS" VARCHAR(2),
   "FTB_FECHALIBERACION" TIMESTAMP,
   "FTB_STATUSLIBERACION" BOOLEAN,
   "FTB_DOCUMENTO" VARCHAR(20) NOT NULL,
   "FTB_MONTO" MONEY,
   "FTB_FACTORORIGINAL" FLOAT,
   "FTB_IMPUESTO" MONEY,
   "FTB_BENEFICIARIO" VARCHAR(80),
   "FTB_CODEBENEFICIARIO" VARCHAR(25),
   "FTB_ORIGENBENEFICIARIO" SMALLINT,
   "FTB_CONCEPTO" VARCHAR(100),
   "FTB_CODECONCEPTO" VARCHAR(25),
   "FTB_MEMODETALLE" MEMO,
   "FTB_NROCOMPROBANTE" VARCHAR(20),
   "FTB_ESDEBITOBANCARIO" BOOLEAN,
   "FTB_ESCHEQUEDEVUELTO" BOOLEAN,
   "FTB_FECHACONCILIACION" DATE,
   "FTB_NUMEROCONCILIACION" INTEGER,
   "FTB_SALDOANTERIOR" MONEY,
   "FTB_AUTOINCREMENTORIGEN" INTEGER,
   "BASE_AUTOINCREMENT" AUTOINC,
   "FTB_MONEDAORIGINAL" VARCHAR(30),
   "FTB_CONTABILIZADO" BOOLEAN,
   "FTB_USER" VARCHAR(10),
   "FTB_HORAOPERACION" TIME,
   "FTB_CLASIFICACION" INTEGER,
   "FTB_CTOCOSTO" VARCHAR(30),
   "FTB_TIPOENDOSO" BOOLEAN,
   "FTB_SUCURSALORIGEN" INTEGER,
   "FTB_FACTORREFERENCIA01" FLOAT,
   "FTB_FACTORREFERENCIA02" FLOAT,
PRIMARY KEY ("FTB_BANCO","FTB_TIPO","FTB_FECHA","BASE_AUTOINCREMENT") COMPRESS NONE
LOCALE CODE 0
USER MAJOR VERSION 1
);

CREATE NOCASE INDEX IF NOT EXISTS "FTB_KEYLIBERACION" ON "Stransbanco" ("FTB_BANCO","FTB_STATUSLIBERACION","FTB_FECHALIBERACION");
CREATE NOCASE INDEX IF NOT EXISTS "FTB_KEYFECHA" ON "Stransbanco" ("FTB_BANCO","FTB_FECHA");
CREATE NOCASE INDEX IF NOT EXISTS "FTB_KEYMONTO" ON "Stransbanco" ("FTB_BANCO","FTB_MONTO");
CREATE NOCASE INDEX IF NOT EXISTS "FTB_KEYDOCUMENTO" ON "Stransbanco" ("FTB_BANCO","FTB_DOCUMENTO","FTB_TIPO");
CREATE NOCASE INDEX IF NOT EXISTS "FTB_KEYCONCEPTO" ON "Stransbanco" ("FTB_BANCO","FTB_CONCEPTO");
CREATE NOCASE INDEX IF NOT EXISTS "FTB_KEYBENEFICIARIO" ON "Stransbanco" ("FTB_BANCO","FTB_BENEFICIARIO");
CREATE NOCASE INDEX IF NOT EXISTS "FTB_KEYORDEN" ON "Stransbanco" ("FTB_BANCO","BASE_AUTOINCREMENT");
CREATE NOCASE INDEX IF NOT EXISTS "FTB_KEYTIPO" ON "Stransbanco" ("FTB_BANCO","FTB_TIPO","FTB_AUTOINCREMENTORIGEN");
CREATE NOCASE INDEX IF NOT EXISTS "FTB_KEYCONCILIA" ON "Stransbanco" ("FTB_BANCO","FTB_STATUS","BASE_AUTOINCREMENT");
CREATE INDEX IF NOT EXISTS "FTB_KEYREPORT" ON "Stransbanco" ("FTB_CODEBENEFICIARIO","FTB_BANCO","FTB_TIPO","FTB_FECHA");
CREATE INDEX IF NOT EXISTS "FTB_KEYLOTE" ON "Stransbanco" ("FTB_BANCO","FTB_TIPO","FTB_DOCUMENTO");
 """
STRANSCUENTA = """ CREATE TABLE IF NOT EXISTS "STransCuentas"
(
   "FE_CODE" AUTOINC,
   "FE_CODECUENTA" VARCHAR(30),
   "FE_BANCOORIGEN" VARCHAR(30),
   "FE_TIPOOPERACION" SMALLINT,
   "FE_TIPOTRANSACCION" SMALLINT,
   "FE_ORIGEN" SMALLINT,
   "FE_VISIBLE" BOOLEAN,
   "FE_OPERACIONAUTOINC" INTEGER,
   "FE_VENTAAUTOINCREMENT" INTEGER,
   "FE_POSARRAYVENTA" INTEGER,
   "FE_DOCUMENTO" VARCHAR(20),
   "FE_MONTO" MONEY,
   "FE_MONTOIMPUESTO" MONEY,
   "FE_MONTOCOMISION" MONEY,
   "FE_FECHA" DATE,
   "FE_FECHAMOVIMIENTO" DATE,
   "FE_STATUS" SMALLINT,
   "FE_DIFERIDO" BOOLEAN,
   "FE_CODECLIENTE" VARCHAR(30),
   "FE_NOLINEA" INTEGER,
   "BASE_AUTOINCREMENT" AUTOINC,
   "FE_AUXILIAR" VARCHAR(30),
   "FE_CTOCOSTO" VARCHAR(30),
   "FE_MTOBASE" MONEY,
   "FE_DESCRIPCIONCOMPROBANTE" MEMO,
   "FE_MTOEFECTIVO" MONEY,
   "FE_ESDEBITOBANCARIO" BOOLEAN,
   "FE_ESNOTA" BOOLEAN,
   "FE_DETALLEMOV" VARCHAR(200),
   "FE_CODEPAGO" VARCHAR(10),
PRIMARY KEY ("FE_CODE") COMPRESS NONE
LOCALE CODE 0
USER MAJOR VERSION 1
);

CREATE INDEX IF NOT EXISTS "FE_KEYFECHA" ON "STransCuentas" ("FE_TIPOTRANSACCION","FE_FECHAMOVIMIENTO","FE_TIPOOPERACION","FE_VENTAAUTOINCREMENT","FE_POSARRAYVENTA");
CREATE INDEX IF NOT EXISTS "FE_KEYDIFERIDO" ON "STransCuentas" ("FE_TIPOTRANSACCION","FE_BANCOORIGEN","FE_DIFERIDO","BASE_AUTOINCREMENT");
CREATE INDEX IF NOT EXISTS "FE_KEYDELETE" ON "STransCuentas" ("FE_TIPOTRANSACCION","FE_OPERACIONAUTOINC");
CREATE INDEX IF NOT EXISTS "FE_KEYLOAD" ON "STransCuentas" ("FE_TIPOTRANSACCION","FE_OPERACIONAUTOINC","FE_VISIBLE","FE_NOLINEA");
CREATE INDEX IF NOT EXISTS "FE_KEYREPORT" ON "STransCuentas" ("FE_TIPOTRANSACCION","FE_CODECUENTA","FE_BANCOORIGEN","FE_FECHAMOVIMIENTO");
"""

A2SISTEMACARGOS = """CREATE TABLE IF NOT EXISTS "a2SistemaCargos"
(
   "FI_CODE" AUTOINC NOT NULL,
   "FI_DETALLE" VARCHAR(250),
   "FI_REFERENCIA" VARCHAR(10) NOT NULL,
   "FI_STATUS" BOOLEAN,
   "FI_RETIENE" BOOLEAN,
   "FI_TIPOALICUOTA" SMALLINT,
   "FI_TIPOCALCULO" SMALLINT,
   "FI_APLICAEN" SMALLINT,
   "FI_SIGLAS" VARCHAR(25),
   "FI_DESCRIPCION" VARCHAR(80),
   "FI_CODERETENCION" VARCHAR(25),
   "FI_VARRETENCIONCOMPRA" VARCHAR(50),
   "FI_RETENCIONCOMPRA" FLOAT,
   "FI_VARRETENCIONVENTA" VARCHAR(50),
   "FI_RETENCIONVENTA" FLOAT,
   "FI_MODIFICA" BOOLEAN,
   "FI_BASEMAYORTR" BOOLEAN,
   "FI_EXCLUYENTE" BOOLEAN,
   "FI_CTACOMPRAS" VARCHAR(35),
   "FI_CTAVENTAS" VARCHAR(35),
   "FI_ESIVA" BOOLEAN,
PRIMARY KEY ("FI_CODE") COMPRESS NONE
LOCALE CODE 0
USER MAJOR VERSION 1
);

CREATE UNIQUE INDEX IF NOT EXISTS "FI_KEYREFERENCIA" ON "a2SistemaCargos" ("FI_REFERENCIA");
"""
A2SISTEMACARGOSALICUOTAS = """CREATE TABLE IF NOT EXISTS "a2SistemaCargosAlicuotas"
(
   "FA_CODE" AUTOINC,
   "FA_IMPUESTO" INTEGER,
   "FA_MONTO" FLOAT,
   "FA_DESCRIPCION" VARCHAR(80),
   "FA_INDEXFISCAL" SMALLINT,
   "FA_CTACOMPRAS" VARCHAR(35),
   "FA_CTAVENTAS" VARCHAR(35),
   "FA_REFERENCIA" VARCHAR(25),
PRIMARY KEY ("FA_CODE") COMPRESS NONE
LOCALE CODE 0
USER MAJOR VERSION 1
);

CREATE INDEX IF NOT EXISTS "FA_KEYALICUOTA" ON "a2SistemaCargosAlicuotas" ("FA_IMPUESTO","FA_CODE");
"""

SOPERACIONINVCARGOS = """CREATE TABLE IF NOT EXISTS "SOperacionInvCargos"
(
   "FTII_AUTO" AUTOINC,
   "FTII_OPERACIONAUTO" INTEGER,
   "FTII_CODEIMPUESTO" INTEGER,
   "FTII_CODEALICUOTA" INTEGER,
   "FTII_CTDITEMSCARGO" INTEGER,
   "FTII_BASECARGO" FLOAT,
   "FTII_ALICUOTACARGO" FLOAT,
   "FTII_MONTOCARGO" FLOAT,
PRIMARY KEY ("FTII_AUTO") COMPRESS NONE
LOCALE CODE 0
USER MAJOR VERSION 1
);

CREATE INDEX IF NOT EXISTS "FTII_KEYDOCUMENTO" ON "SOperacionInvCargos" ("FTII_OPERACIONAUTO");
"""